### ISSUE TITLE
[Feature 7A] Updating Visited / Likes List in the Database

### ISSUE THREAD

**Issue by chloe2407** [CSC207-2022F-UofT/course-project-group-80#8]
Once current user has liked/disliked a user, that user is updated in the visited and likes list in the database.

**Comment by LanceLi1416** [comment]
Considering our current progress, we may have to wait until [Database Access Interface #1](#1) (PR [here](#28)) is up and running, and is merged into main. @chloe2407 please let me know if this is holding anything back. Thank you!

**Comment by chloe2407** [comment]
It is not a big issue that is holding anything back. I talked with Jess earlier and she said that the User methods setViewed() and setLiked() should update it to the database, but not sure if that is that is how it works. Without this method, it would just not update the two lists in the User database.
